# Dependencies
# $ gem install rouge
# $ rougify style base16.solarized > assets/css/highlighter.css
highlighter: rouge

# Custom variables
repository: "https://github.com/vsn4ik/bootstrap-submenu"
version: 3.0.1
name: "Bootstrap-submenu"
description: "Bootstrap Sub-Menus"
keywords: "bootstrap dropdown jquery-plugin submenu"

author:
  name: "Vasilii A."

cdn:
  bootstrap:
    css: "https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.css"
    js: "https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.js"

  jquery:
    js: "https://code.jquery.com/jquery-3.5.1.slim.js"

  popper:
    js: "https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.js"

  fa:
    css: "https://use.fontawesome.com/releases/v5.15.1/css/all.css"
